### ISSUE TITLE
testnet problems 

### ISSUE THREAD

**Issue by tieandsuit** [xel-software/xel-computation-wallet#7]
unsure what happened but speed shart not working anymore after testnet restart.
Please confirm that it's not just my xeline client 

![Screenshot_7](https://user-images.githubusercontent.com/43476731/59781216-a8338880-92bb-11e9-96fb-fef1a20758cd.png)

**Comment by any1one** [comment]
Not sure where the issue comes from, that would require several cross-checks :
- Your xeline client against the mainnet 
- If you updated xeline, use an older client and try again
- Maybe use and older miner

Those results could point where is the problem

**Comment by tieandsuit** [comment]
Miner and xeline same as was before reboot of testnet. Regardless, will do more testing.

**Comment by any1one** [comment]
and the miner is working fine since then ?

**Comment by tieandsuit** [comment]
Yes, all good. Just this glich in network speed chart.

**Comment by any1one** [comment]
ok so xeline is checking this : `http://testnet-01.xel.org:16876/nxt?requestType=getState&includeLastTargets=true&includeTasks=true`

And use the lastTargets to compute the mips value like this : 

`assets/status.js`
```
var targets = event[6];
    var labels = [];
    var data = [];
    var currentmips = 0;
    for (var i = targets.length - 1; i >= 0; i--) {
        var dct = targets[i];
        var localmips = 0;
        labels.push(Object.keys(dct)[0]);
        var tgt = dct[Object.keys(dct)[0]];
        var scaler = 8789596572746 * 0.9; // empirically
        localmips = Math.round((scaler / tgt) * 57.5);
        //console.log("mips " + localmips);
        data.push(localmips);
        if (i == 0) currentmips = localmips;
    }
    cp.innerHTML = currentmips;
```

And the values of lastTargets are set with this : 
`src/main/java/org/xel/http/GetState.java`
```
if(includeLastTargets){
            JSONArray arr = new JSONArray();
            int counter = 0;
            Block bl = Nxt.getTemporaryComputationBlockchain().getLastBlock();
            for(counter=0; counter < 6; counter++){
                if(bl==null) break;
                JSONObject obj = new JSONObject();
                obj.put(bl.getHeight(), bl.getPowTarget());
                arr.add(obj);
                bl=Nxt.getTemporaryComputationBlockchain().getBlock(bl.getPreviousBlockId());
            }
            response.put("lastTargets", arr);
        }
```

I don't have time to go into the details for now, but if you look at how the `getPowTarget()` works, and if you somehow can make sense of the mips calculation in xeline (i can't), you should have your answer.

Everything is explained by looking at the code, but long story short i would not hold my breath about the accuracy of this mips value

**Comment by tieandsuit** [comment]
Problem was on testnet that was fresh restart and needed some time for computation blockchain, its not a bug. closing issue
